INSERT INTO `mydb`.`Cars` (`idCars`, `VIN`, `Manufacturer`, `Model`, `Year`, `Color`) VALUES ('0', '3K096I98581DHSNUP', 'Volkswagen', 'Tiguan', 2019, 'Blue');
INSERT INTO `mydb`.`Cars` (`idCars`, `VIN`, `Manufacturer`, `Model`, `Year`, `Color`) VALUES ('1', 'ZM8G7BEUQZ97IH46V', 'Peugeot', 'Rifter', 2019, 'Red');
INSERT INTO `mydb`.`Cars` (`idCars`, `VIN`, `Manufacturer`, `Model`, `Year`, `Color`) VALUES ('2', 'RKXVNNIHLVVZOUB4M', 'Ford', 'Fusion', 2018, 'White');
INSERT INTO `mydb`.`Cars` (`idCars`, `VIN`, `Manufacturer`, `Model`, `Year`, `Color`) VALUES ('3', 'HKNDGS7CU31E9Z7JW', 'Toyota', 'RAV4', 2018, 'Silver');
INSERT INTO `mydb`.`Cars` (`idCars`, `VIN`, `Manufacturer`, `Model`, `Year`, `Color`) VALUES ('4', 'DAM41UDN3CHU2WVF6', 'Volvo', 'V60', 2019, 'Gray');
INSERT INTO `mydb`.`Cars` (`idCars`, `VIN`, `Manufacturer`, `Model`, `Year`, `Color`) VALUES ('5', 'DAM41UDN3CHU2WVF6', 'Volvo', 'V60 Cross Country', 2019, 'Gray');
INSERT INTO `mydb`.`Customers` (`idCustomers`, `Customer ID`, `Name`, `Phone`, `Email`, `Address`, `City`, `State/Province`, `Country`, `Postal`) VALUES ('0', '10001', 'Pablo Picasso', '+34 636 17 63 82', '-', 'Paseo de la Chopera, 14', 'Madrid', 'Madrid', 'Spain', '28045');
INSERT INTO `mydb`.`Customers` (`idCustomers`, `Customer ID`, `Name`, `Phone`, `Email`, `Address`, `City`, `State/Province`, `Country`, `Postal`) VALUES ('1', '20001', 'Abraham Lincoln', '+1 305 907 7086', '-', '120 SW 8th St', 'Miami', 'Florida', 'United States', '33130');
INSERT INTO `mydb`.`Customers` (`idCustomers`, `Customer ID`, `Name`, `Phone`, `Email`, `Address`, `City`, `State/Province`, `Country`, `Postal`) VALUES ('2', '30001', 'Napoléon Bonaparte', '+33 1 79 75 40 00', '-', '40 Rue du Colisée', 'Paris', 'Île-de-France', 'France', '75008');
INSERT INTO `mydb`.`Salespersons` (`idSalespersons`, `Staff ID`, `Name`, `Store`) VALUES ('0', '00001', 'Petey Cruiser', 'Madrid');
INSERT INTO `mydb`.`Salespersons` (`idSalespersons`, `Staff ID`, `Name`, `Store`) VALUES ('1', '00002', 'Anna Sthesia', 'Barcelona');
INSERT INTO `mydb`.`Salespersons` (`idSalespersons`, `Staff ID`, `Name`, `Store`) VALUES ('2', '00003', 'Paul Molive', 'Berlin');
INSERT INTO `mydb`.`Salespersons` (`idSalespersons`, `Staff ID`, `Name`, `Store`) VALUES ('3', '00004', 'Gail Forcewind', 'Paris');
INSERT INTO `mydb`.`Salespersons` (`idSalespersons`, `Staff ID`, `Name`, `Store`) VALUES ('4', '00005', 'Paige Turner', 'Mimia');
INSERT INTO `mydb`.`Salespersons` (`idSalespersons`, `Staff ID`, `Name`, `Store`) VALUES ('5', '00006', 'Bob Frapples', 'Mexico City');
INSERT INTO `mydb`.`Salespersons` (`idSalespersons`, `Staff ID`, `Name`, `Store`) VALUES ('6', '00007', 'Walter Melon', 'Amsterdam');
INSERT INTO `mydb`.`Salespersons` (`idSalespersons`, `Staff ID`, `Name`, `Store`) VALUES ('7', '00008', 'Shonda Leer', 'São Paulo');
INSERT INTO `mydb`.`Invoices` (`idInvoices`, `Invoice Number`, `Date`, `Cars_idCars`, `Customers_idCustomers`, `Salespersons_idSalespersons`) VALUES (NULL, '852399038', '22-08-2018', '1', '2', '4');
INSERT INTO `mydb`.`Invoices` (`idInvoices`, `Invoice Number`, `Date`, `Cars_idCars`, `Customers_idCustomers`, `Salespersons_idSalespersons`) VALUES (NULL, '731166526', '31-12-2018', '4', '1', '6');
INSERT INTO `mydb`.`Invoices` (`idInvoices`, `Invoice Number`, `Date`, `Cars_idCars`, `Customers_idCustomers`, `Salespersons_idSalespersons`) VALUES (NULL, '271135104', '22-01-2019', '3', '3', '8');
